openapi: 3.0.0
info:
  title: MCP Weather Tool
  version: 1.0.0
  description: Query current weather by city name
paths:
  /v1/mcp:
    post:
      summary: Query weather
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id: { type: string }
                jsonrpc: { type: string }
                method: { type: string, example: weather }
                params:
                  type: object
                  properties:
                    city:
                      type: string
                      example: 東京
      responses:
        '200':
          description: JSON-RPC Result
